# Generated by Django 2.2.1 on 2019-05-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_to_book', models.TextField(verbose_name='Комментарий к книге')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('commented_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_book', to='books.Book', verbose_name='Книга с комментарием')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
