# Generated by Django 2.2 on 2019-04-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_binding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Binding',
            new_name='Publish',
        ),
    ]
