# Generated by Django 2.1.7 on 2019-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_binding_bookformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
