# Generated by Django 2.2.1 on 2019-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Имя'),
        ),
    ]
