# Generated by Django 2.2.1 on 2019-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_auto_20190607_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Имя'),
        ),
    ]
