# Generated by Django 2.1.7 on 2019-04-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20190406_2011'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.BookFormat', verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(default=0, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, гр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.PositiveSmallIntegerField(verbose_name='Количество страниц'),
        ),
    ]
