# Generated by Django 2.1.7 on 2019-04-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20190406_2011'),
        ('books', '0002_auto_20190406_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во книг в наличии'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Publish', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_day',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
