# Generated by Django 2.1.7 on 2019-04-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190406_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.BookFormat', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
    ]
