# Generated by Django 2.1.7 on 2019-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190406_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='ISBN'),
        ),
    ]
