# Generated by Django 2.1.7 on 2019-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190407_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='ISBN'),
        ),
    ]
