# Generated by Django 2.1.7 on 2019-04-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190408_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='reference.Binding', verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='reference.BookFormat', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='reference.Publish', verbose_name='Издательство'),
        ),
    ]
