# Generated by Django 2.2.1 on 2019-05-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190411_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_edit', 'can edit content')], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
