# Generated by Django 2.2.1 on 2019-05-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20190524_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('edit-content', 'for content-managers'), ('edit-order', 'for edit-managers'), ('market', 'for marketers')], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
