# Generated by Django 2.2.1 on 2019-05-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0009_orderstatus'),
        ('cart', '0003_auto_20190513_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('email', models.EmailField(blank=True, help_text='very_good_user@mail.com', max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(help_text='+375-33-111-42-42', max_length=17, verbose_name='Контактный телефон')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в корзину')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.OrderStatus', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
